from __future__ import annotations

import logging

import pytest

from bookwiki.agents.lesson_agent import LessonAgent
from bookwiki.scheduler.cache import run_with_cache, task_key
from tests.fakes import RecordingRuntime


def _lesson_response() -> dict[str, object]:
    citation = {"ref_id": "source-p001", "quote": "hello"}
    return {
        "chapter_id": "ch01",
        "chapter": {
            "chapter_id": "ch01",
            "title": "Foundations",
            "body_md": "# Foundations\n\nGenerated by fake LLM.",
            "concepts": ["state"],
            "citations": [citation],
            "owner_task_id": "ch01:chapter",
        },
        "quiz": {
            "chapter_id": "ch01",
            "items": [],
            "placements": [],
            "owner_task_id": "ch01:quiz",
        },
        "card": {
            "chapter_id": "ch01",
            "items": [],
            "owner_task_id": "ch01:card",
        },
        "owner_task_id": "ch01:lesson",
    }


def _payload() -> dict[str, str]:
    return {
        "chapter_id": "ch01",
        "title": "Foundations",
        "source_md": "<!-- source_ref: source-p001 -->\nhello",
    }


def test_task_key_is_stable_and_input_sensitive() -> None:
    first = task_key(LessonAgent, {"chapter": "ch01"}, model="stub")
    second = task_key(LessonAgent, {"chapter": "ch01"}, model="stub")
    changed = task_key(LessonAgent, {"chapter": "ch02"}, model="stub")

    assert first == second
    assert first != changed


@pytest.mark.asyncio
async def test_run_with_cache_marks_second_call_as_hit(tmp_path) -> None:
    cache_dir = tmp_path / ".cache"
    runtime = RecordingRuntime([_lesson_response()])
    first = await run_with_cache(
        LessonAgent, _payload(), model="stub", cache_dir=cache_dir, runtime=runtime
    )
    second = await run_with_cache(
        LessonAgent, _payload(), model="stub", cache_dir=cache_dir, runtime=runtime
    )

    assert first.result.chapter_id == "ch01"
    assert first.cache_hit is False
    assert second.cache_hit is True
    assert second.result.model_dump() == first.result.model_dump()
    assert len(runtime.calls) == 1


@pytest.mark.asyncio
async def test_run_with_cache_logs_agent_start_done_and_cache_hit(
    tmp_path, caplog: pytest.LogCaptureFixture
) -> None:
    cache_dir = tmp_path / ".cache"
    runtime = RecordingRuntime([_lesson_response()])

    with caplog.at_level(logging.INFO):
        await run_with_cache(
            LessonAgent, _payload(), model="stub", cache_dir=cache_dir, runtime=runtime
        )
        await run_with_cache(
            LessonAgent, _payload(), model="stub", cache_dir=cache_dir, runtime=runtime
        )

    messages = "\n".join(record.getMessage() for record in caplog.records)

    assert "agent start agent=LessonAgent model=stub" in messages
    assert "agent done agent=LessonAgent model=stub" in messages
    assert "agent cache_hit agent=LessonAgent model=stub" in messages
