from __future__ import annotations

from typing import Literal

import yaml
from pydantic import Field, field_validator

from bookwiki.schemas.common import VersionedModel


class _IndentedSafeDumper(yaml.SafeDumper):
    """Dump nested sequences with an extra indent level (block style, no flow)."""

    def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:
        return super().increase_indent(flow, False)


class SourceSummaryResult(VersionedModel):
    source_id: str
    summary_md: str
    source_refs: list[str] = Field(default_factory=list)
    detected_chapter_id: str | None = None
    detected_title: str | None = None
    headings: list[str] = Field(default_factory=list)
    key_terms: list[str] = Field(default_factory=list)


class ChapterProposal(VersionedModel):
    title: str
    topics: list[str] = Field(default_factory=list)
    source_refs: list[str] = Field(default_factory=list)


class StructureResult(VersionedModel):
    chapters: list[ChapterProposal] = Field(default_factory=list)

    @property
    def proposed_structure_yaml(self) -> str:
        """Render the structured chapters to YAML.

        The YAML is generated by ``yaml.dump`` (not hand-written by the LLM), so it is
        always syntactically valid: titles/topics containing ``:`` are quoted
        automatically, unlike a free-text string the model emits itself.
        """

        payload = {
            "chapters": [
                {
                    "title": chapter.title,
                    "topics": list(chapter.topics),
                    "source_refs": list(chapter.source_refs),
                }
                for chapter in self.chapters
            ]
        }
        return yaml.dump(
            payload,
            Dumper=_IndentedSafeDumper,
            sort_keys=False,
            allow_unicode=True,
        )


class ChapterSplitResult(VersionedModel):
    chapters: dict[str, str] = Field(default_factory=dict)
    chapter_titles: dict[str, str] = Field(default_factory=dict)
    alignment: list[dict[str, object]] = Field(default_factory=list)
    coverage: dict[str, float | int] = Field(default_factory=dict)
    report_md: str


class ChapterSplitAuditResult(VersionedModel):
    report_md: str


class RepairResult(VersionedModel):
    owner_task_id: str
    action: str
    notes: str


class SourceLayoutPatch(VersionedModel):
    action: Literal[
        "link_table_parts",
        "attach_caption",
        "promote_heading",
        "demote_repeating_header_footer",
    ]
    source_block_id: str
    target_block_id: str | None = None
    confidence: float = 0.0
    reason: str = ""

    @field_validator("source_block_id", "target_block_id", "reason")
    @classmethod
    def strip_strings(cls, value: str | None) -> str | None:
        if value is None:
            return None
        return value.strip()


class SourceLayoutRepairResult(VersionedModel):
    patches: list[SourceLayoutPatch] = Field(default_factory=list)
    notes: str = ""


class VisionCaptionResult(VersionedModel):
    caption_md: str
    key_points: list[str] = Field(default_factory=list)
    source_ref: str
    confidence: float = 0.0
